### PR TITLE
Update theme to 1.4

### PR DESCRIPTION
**Pull request by gamebits**
Updates the twentytwentyone theme to v1.4, released on 20 Jul 2021, coinciding with WordPress 5.8. [Changelog](https://wordpress.org/support/article/twenty-twenty-one-changelog#Version_1.4)

### CODE REVIEW

**Review by gudmdharalds — COMMENTED** [review]
I had a look at the PR. While most of the content is the same as in the `5.8` WordPress release, there are differences:

* A number of `*.css.map` files found in the PR are not found in the WordPress release. 
* Files in `assets/sass/` are missing from the PR while they are found in the WordPress release.
* `package.json` is found in the WordPress release but not in the PR.

Is there any specific reason for these differences?

**Comment by gamebits** [comment]
Thank you for the review, @gudmdharalds !

> A number of *.css.map files found in the PR are not found in the WordPress release.

Which are those? I downloaded the theme from the [WordPress.org theme repository](https://wordpress.org/themes/twentytwentyone/), and it contains these six files:

- assets/css/ie-editor.css.map
- assets/css/ie.css.map
- assets/css/print.css.map
- assets/css/style-dark-mode.css.map
- assets/css/style-editor.css.map
- assets/css/style.css.map

As for missing files, is it possible those files did not change from v1.3 to v1.4 and thus were not overwritten by the PR? For example, `package.json` has a modification date of 27 Apr 2021, so it would've been included in the 1.3 PR on 2 June 2021. https://github.com/Automattic/vip-go-skeleton/pull/72

If you'd like me to resubmit the PR so it contains all files, not just updated ones, let me know!

**Comment by gudmdharalds** [comment]
> As for missing files, is it possible those files did not change from v1.3 to v1.4 and thus were not overwritten by the PR? For example, package.json has a modification date of 27 Apr 2021, so it would've been included in the 1.3 PR on 2 June 2021. #72

I actually based the comparison on the files in the branch (`twentytwentyone-1.4`) that the PR points to. I also based my comparison on the WordPress 5.8 ZIP file, not the theme repository. I should have been more specific, my apologies. 

> If you'd like me to resubmit the PR so it contains all files, not just updated ones, let me know!

I think it is safest to keep the repository in sync with the WordPress release, so I think it makes sense to submit the missing files.

**Comment by gamebits** [comment]
> * Files in assets/sass/ are missing from the PR while they are found in the WordPress release.
> * package.json is found in the WordPress release but not in the PR.

These files are listed in this theme's `.gitignore` [file](https://github.com/Automattic/vip-go-skeleton/blob/master/.gitignore), which is why they were omitted when I pushed from local.

As for the `.map` files, I didn't realize there was a difference between the theme in the repository and the theme included in core. How interesting! I've made [a commit](https://github.com/Automattic/vip-go-skeleton/pull/73/commits/d41e3dc3e3c87fc1752e4bd2e740d69ca7858d03) that should bring this PR into alignment with the latter.

**Comment by gudmdharalds** [comment]
Thanks @gamebits !

No further feedback from me, but I think it is best if someone from Platform reviews and approves this PR.

**Review by rinatkhaziev — APPROVED** [review]

**Pull request merged**
